// CONVERSION OF DATATYPES
let score = "33abc"

// console.log(typeof score);

// console.log(typeof (score));

let valueInNumber = Number(score)


// console.log(typeof valueInNumber)

// console.log(valueInNumber)

//"33" => 33

//"33abc"

// 1 => TRUE 0 =>FALSE

//"" => FALSE

//"ABC" =>TRUE

//*****************************OPERATIONS******************************* */

let value = 3

let negValue = -value

// console.log(negValue);

let str1 = "Hello"

let str2 = " Palkesh"

let str3 = str1+str2;

// console.log(str3);

console.log("1" + 2); // =>12
console.log(1 + "2"); // => 12
console.log("1" + 2 + 2); // =>122
console.log(1 + 2 + "2") // => 32