// VALUE OF THIS IN BRWOSER => WINDOW OBJECT

//EXECUTION CONTEXT
//1. GLOBAL EXECUTION CONTEXT
//2. FUNCTION EXECUTION CONTEXT
//3. EVAL EXECUTION CONTEXT

// 

// MEMORY CREATION PHASE => MEMORY ALLOCATION (MCP/CP)

// Execution phase =>